### ISSUE TITLE
Compiling error with OpenSSL 1.1.0

### ISSUE THREAD

**Issue by 1ucian0** [jmk-foofus/medusa#12]
Medusa does not compile with OpenSSL 1.1.0 (see https://bugs.debian.org/828433).

In particular:

```
wrapper.o -MD -MP -MF $depbase.Tpo -c -o wrapper.o wrapper.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo ../medusa-trace.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
x86_64-linux-gnu-gcc -DHAVE_CONFIG_H -I. -I../..  -I../../src  -Wdate-time -D_FORTIFY_SOURCE=2 -g -DDEBUG -fPIC -I/usr/include -I/usr/local/include -I/usr/include/postgresql -I/usr/include/pgsql -I/usr/include/afpfs-ng -I/usr//include  -I/usr/include/apr-1.0   -DLINUX -D_REENTRANT -D_GNU_SOURCE  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -MT ../medusa-trace.o -MD -MP -MF $depbase.Tpo -c -o ../medusa-trace.o ../medusa-trace.c &&\
mv -f $depbase.Tpo $depbase.Po
vnc.c: In function 'sendAuthMSLogin':
vnc.c:815:12: error: dereferencing pointer to incomplete type 'DH {aka struct dh_st}'
   dh_struct->g = BN_new();
            ^
Makefile:815: recipe for target 'vnc.o' failed
make[4]: *** [vnc.o] Error 1
make[4]: *** Waiting for unfinished jobs....
make[4]: Leaving directory '/<<PKGBUILDDIR>>/src/modsrc'
Makefile:433: recipe for target 'all-recursive' failed
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory '/<<PKGBUILDDIR>>/src'
Makefile:438: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/<<PKGBUILDDIR>>'
Makefile:335: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/<<PKGBUILDDIR>>'
debian/rules:27: recipe for target 'build-stamp' failed
make: *** [build-stamp] Error 2
dpkg-buildpackage: error: debian/rules build-arch gave error exit status 2
```

**Comment by rhertzog** [comment]
Should be fixed with https://github.com/jmk-foofus/medusa/commit/349ef7f0c24b627c6dbba8bcd5b47173806473a2 (if we trust the commit description at least).

**Comment by jmk-foofus** [comment]
rhertzog- You're correct, this commit was to allow Medusa to compile against OpenSSL 1.1.0b. I can release 2.2.1 once I've had a chance to do some additional testing. Is there a specific date coming up I should release by to meet Debian targets?

**Comment by rhertzog** [comment]
https://release.debian.org/ It's probably best to release it in 2016.

**Comment by lbello** [comment]
On Thursday, 3 November 2016 11:06:12 EDT jmk-foofus wrote:
> rhertzog- You're correct, this commit was to allow Medusa to compile against
> OpenSSL 1.1.0b. I can release 2.2.1 once I've had a chance to do some
> additional testing. Is there a specific date coming up I should release by
> to meet Debian targets?

I uploaded with 2.2-4 to Debian Sid with https://github.com/jmk-foofus/medusa/
commit/349ef7f0c24b627c6dbba8bcd5b47173806473a2 to allow openssl 1.1.

Cheers, luciano

PS: JMK, of course we can still update to 2.2.1 whenever you think is ready.

**Comment by blshkv** [comment]
Please make a release. Thank you.
